### PR TITLE
Fix story

### PR DESCRIPTION
**Pull request by Hypnosphi**

### CODE REVIEW

**Comment by leetercola** [comment]
@Hypnosphi is there a way to clean up the stories ui after you leave the story clicked? Currently every time you visit this modal it adds another portal to the dom and you can't clear the screen or view any other stories afterwards. The React Portal is still outside of the iframe so any new stories displaying are underneath the portal it seems

**Comment by Hypnosphi** [comment]
I tried to add another story to that repo and I can't actually reproduce the issue. The portal is always inside iframe, and always gets removed when leaving the modal story:
kapture 2018-01-17 at 21 51 20

**Comment by leetercola** [comment]
I pushed a change that actually uses enzyme and shallow mounts the modal. It seems like the mount call is creating an additional modal content on the page and this was the behavior I was experiencing. It doesn't look like a storybook thing and I doubt there is much I can do about it until enzyme properly absorbs the portal element which is directly attaching to dom. @Hypnosphi

**Comment by Hypnosphi** [comment]
> shallow mounts

What do you mean by that? AFAIK enzyme can either __shallow__ render (that is, basically just call `render` function without doing anything with DOM), or __mount__. To test portals, you probably need the latter

**Comment by leetercola** [comment]
Enzyme.shallow which is supposed to be a virtual render

**Comment by Hypnosphi** [comment]
You can use `mount`, but you'll probably need to `unmount()` the wrapper manually:

http://airbnb.io/enzyme/docs/api/mount.html
> Note: unlike shallow or static rendering, full rendering actually mounts the component in the DOM, which means that tests can affect each other if they are all using the same DOM. Keep that in mind while writing your tests and, if necessary, use `.unmount()` or something similar as cleanup.

**Comment by praWINK** [comment]
@Hypnosphi @leetercola I am also having the same issue, my react and reactDOM version is 16.5.2, but I am facing  **react_dom___default.a.createPortal is not a function**.

**Comment by exoer** [comment]
I appended the DOM element that my portal needs in the story
`

      .add('terms dialog', () => {
        var newNode = document.createElement('div')
        newNode.setAttribute('id', 'modal')
        const rootNode = document.querySelector('#root')
        rootNode.after(newNode)
        
        return (
          <div className='vh-100'>      
            <TermsDialog initialOpen={true} />
          </div>
        )
      })


`

**Pull request merged**
